// code/frontend/libs/canvas-mark/docs/demo/Mark.vue
<template>
	<div class="mark-container"></div>
</template>

<script lang="ts">
import { PropType, defineComponent, getCurrentInstance, onBeforeUnmount, onMounted } from 'vue';
import { PageItem } from '@/components/mark/helpers/types';
import { type MarkInstance, type MarkInitOptions, type RenderMode, createMark } from 'canvas-mark';
import { useResizeListener } from '@/utils/util';
import { Func } from '@/types';

export default defineComponent({
	name: 'Mark',
	props: {
		options: {
			type: Object as PropType<MarkInitOptions>,
			default: () => ({}),
		},
		pages: {
			type: Array as PropType<PageItem[]>,
			default: () => [],
		},
		pageIndex: {
			type: Number,
			default: 1,
		},
		getLocation: {
			type: Function as PropType<(pageItem: any) => any>,
		},
		mode: {
			type: String as PropType<RenderMode>,
		},
	},
	setup(props) {
		const vm = getCurrentInstance()?.proxy as any;
		const { options, pages, getLocation, mode } = props;
		const instance = { value: null as MarkInstance | null };
		let containerResizeDestroy: Func | undefined;

		const initMark = () => {
			instance.value = createMark({
				...options,
				selector: vm.$el,
				pages: pages,
				multiple: true,
				mode,
				getLocation,
				onChangePage(i: number, pageItem: any) {
					vm.$emit('update:page-index', i);
					vm.$emit('change-page', i);
				},
				onContainerSizeChange() {},
				onTranslateChange() {},
				onMarkHover(shape: any) {
					vm.$emit('mark-hover', shape);
				},
				onMarkLeave(shape: any) {
					vm.$emit('mark-leave', shape);
				},
				onMarkNoHover(e) {},
				onMarkClick(shape: any, e: Event) {
					console.log('shape :>> ', shape);
					vm.$emit('mark-click', shape);
				},
				onMarkRightClick(shape: any) {
					vm.$emit('mark-right-click', shape);
				},
				onDrawComplete(shape: any) {
					// console.log('onDrawComplete data :>> ', shape);
				},
			});
			if (!instance.value) return;

			const { init, rerender } = instance.value;
			init();
			vm.$emit('init', instance.value);
			containerResizeDestroy = useResizeListener(vm.$el, rerender, { enableFrame: true });
		};

		onMounted(() => {
			initMark();
		});

		onBeforeUnmount(() => {
			containerResizeDestroy?.();
		});

		return {
			init: () => instance.value?.init(),
			destroy: () => instance.value?.destroy(),
			reset: () => instance.value?.reset(),
			render: (...args: Parameters<MarkInstance['render']>) => instance.value?.render(...args),
			enableDrawShape: (...args: Parameters<MarkInstance['enableDrawShape']>) => instance.value?.enableDrawShape(...args),
			cancelDrawShape: (...args: Parameters<MarkInstance['cancelDrawShape']>) => instance.value?.cancelDrawShape(...args),
			setMode: (...args: Parameters<MarkInstance['setMode']>) => instance.value?.setMode(...args),
			changePage: (...args: Parameters<MarkInstance['changePage']>) => instance.value?.changePage(...args),
			drawRect: (...args: Parameters<MarkInstance['drawRect']>) => instance.value?.drawRect(...args),
			removeRect: (...args: Parameters<MarkInstance['removeRect']>) => instance.value?.removeRect(...args),
			getInternalPage: (...args: Parameters<MarkInstance['getInternalPage']>) => instance.value?.getInternalPage(...args),
			setScaleByRadio: (...args: Parameters<MarkInstance['setScaleByRadio']>) => instance.value?.setScaleByRadio(...args),
			queryState: (...args: Parameters<MarkInstance['queryState']>) => instance.value?.queryState(...args),
			queryAllState: (...args: Parameters<MarkInstance['queryAllState']>) => instance.value?.queryAllState(...args),
			setActive: (...args: Parameters<MarkInstance['setActive']>) => instance.value?.setActive(...args),
			getActive: (...args: Parameters<MarkInstance['getActive']>) => instance.value?.getActive(...args),
		};
	},
});
</script>

<style>
.mark-container {
	position: relative;
	width: 100%;
	height: 100%;
	background-color: #fff;
}
</style>

// code/frontend/libs/canvas-mark/docs/demo/Mark.tsx
'use client';

import { MarkInstance, MarkInitOptions, RenderMode, createMark, PageItem, MarkOptions } from 'canvas-mark';
import { useResizeListener } from '@/utils/util';
import { ForwardedRef, forwardRef, useCallback, useEffect, useImperativeHandle, useLayoutEffect, useRef } from 'react';
import { Func } from '@/types';
import styles from './mark.module.less';
import { PageMarkItem } from './types';

export interface MarkProps {
	options?: Partial<MarkOptions>;
	pages: PageMarkItem[];
	pageIndex?: number;
	onPageChange?: (page: number, pageItem?: PageItem) => void;
	mode?: RenderMode;
	getLocation?: (pageItem: PageItem) => any;
	onMarkNoHover?: Func;
	onMarkHover?: Func;
	onMarkClick?: Func;
	onMarkLeave?: Func;
	onMarkRightClick?: Func;
	onDrawStart?: Func;
	onDrawComplete?: Func;
	onDrawCancel?: Func;
	onDrawChange?: Func;
	onDrawRemove?: Func;
	onInit?: Func;
}

export type MarkExportProps = MarkInstance;

export default forwardRef<MarkExportProps, MarkProps>(function Mark(props: MarkProps, ref) {
	const {
		options = {},
		pages,
		getLocation,
		mode,
		onInit,
		onPageChange,
		onMarkNoHover,
		onMarkHover,
		onMarkLeave,
		onMarkClick,
		onMarkRightClick,
		onDrawComplete,
	} = props;
	const instance = useRef<MarkInstance>();
	let containerResizeDestroy: Func | undefined;
	const containerRef = useRef<any>();

	useImperativeHandle(ref, () => {
		return {
			init: (...args: Parameters<MarkInstance['init']>) => instance.current?.init(...args),
			destroy: () => instance.current?.destroy(),
			reset: () => instance.current?.reset(),
			render: (...args: Parameters<MarkInstance['render']>) => instance.current?.render(...args),
			enableDrawShape: (...args: Parameters<MarkInstance['enableDrawShape']>) => instance.current?.enableDrawShape(...args),
			cancelDrawShape: (...args: Parameters<MarkInstance['cancelDrawShape']>) => instance.current?.cancelDrawShape(...args),
			setMode: (...args: Parameters<MarkInstance['setMode']>) => instance.current?.setMode(...args),
			changePage: (...args: Parameters<MarkInstance['changePage']>) => instance.current?.changePage(...args),
			drawRect: (...args: Parameters<MarkInstance['drawRect']>) => instance.current?.drawRect(...args),
			removeRect: (...args: Parameters<MarkInstance['removeRect']>) => instance.current?.removeRect(...args),
			getInternalPage: (...args: Parameters<MarkInstance['getInternalPage']>) => instance.current?.getInternalPage(...args),
			setScaleByRadio: (...args: Parameters<MarkInstance['setScaleByRadio']>) => instance.current?.setScaleByRadio(...args),
			queryState: (...args: Parameters<MarkInstance['queryState']>) => instance.current?.queryState(...args),
			getPageState: (...args: Parameters<MarkInstance['getPageState']>) => instance.current?.getPageState(...args),
			queryAllState: (...args: Parameters<MarkInstance['queryAllState']>) => instance.current?.queryAllState(...args),
			setActive: (...args: Parameters<MarkInstance['setActive']>) => instance.current?.setActive(...args),
			getActive: (...args: Parameters<MarkInstance['getActive']>) => instance.current?.getActive(...args),
		} as any;
	});

	const initMark = useCallback(() => {
		instance.current = createMark({
			...options,
			selector: containerRef.current,
			pages: pages as any[],
			multiple: true,
			mode,
			getLocation,
			onChangePage(i: number, pageItem: any) {
				onPageChange?.(i, pageItem);
			},
			onContainerSizeChange() {},
			onTranslateChange() {},
			onMarkHover,
			onMarkLeave,
			onMarkNoHover,
			onMarkClick,
			onMarkRightClick,
			onDrawComplete,
		});
		if (!instance.current) return;

		const { init, rerender } = instance.current;
		init();
		onInit?.(instance.current);
		// eslint-disable-next-line react-hooks/rules-of-hooks
		containerResizeDestroy = useResizeListener(containerRef.current, rerender, { enableFrame: true });
	}, []);

	useEffect(() => {
		initMark();
		return containerResizeDestroy;
	}, [pages]);

	return <div ref={containerRef} className={styles['mark-container']}></div>;
});
